// Shared sample data for the DrivePass UI kits — real car photos (Unsplash).
window.DP_CARS = [
  { id: 1, marca: "Mazda", modelo: "CX-5", anio: 2023, tipo: "SUV", ubicacion: "El Poblado", precioDia: 180000, descripcion: "SUV full equipo, automático. Ideal para viajes en familia por Antioquia.", transmision: "Automática", combustible: "Gasolina", pasajeros: 5, placa: "KXR 482", foto: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=900&q=80&auto=format&fit=crop", verificado: true },
  { id: 2, marca: "Toyota", modelo: "Corolla", anio: 2022, tipo: "Sedán", ubicacion: "Laureles", precioDia: 120000, descripcion: "Económico, cómodo y muy confiable para moverte por la ciudad.", transmision: "Automática", combustible: "Gasolina", pasajeros: 5, placa: "HJD 119", foto: "https://images.unsplash.com/photo-1623869675781-80aa31012a5a?w=900&q=80&auto=format&fit=crop", verificado: true },
  { id: 3, marca: "Porsche", modelo: "911 Carrera", anio: 2021, tipo: "Lujo", ubicacion: "El Poblado", precioDia: 690000, descripcion: "Deportivo premium para una ocasión especial. Reserva con anticipación.", transmision: "Automática", combustible: "Gasolina", pasajeros: 2, placa: "PRS 911", foto: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=900&q=80&auto=format&fit=crop", verificado: true },
  { id: 4, marca: "Ford", modelo: "Ranger", anio: 2023, tipo: "Pickup", ubicacion: "Envigado", precioDia: 240000, descripcion: "Pickup 4x4 lista para carretera y carga. Doble cabina.", transmision: "Manual", combustible: "Diésel", pasajeros: 5, placa: "FRG 770", foto: "https://images.unsplash.com/photo-1605893477799-b99a3b8b8f0e?w=900&q=80&auto=format&fit=crop", verificado: true },
  { id: 5, marca: "Tesla", modelo: "Model 3", anio: 2023, tipo: "Eléctrico", ubicacion: "Belén", precioDia: 0, descripcion: "100% eléctrico, autopiloto. Estamos verificando este vehículo.", transmision: "Automática", combustible: "Eléctrico", pasajeros: 5, placa: "TSL 303", foto: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=900&q=80&auto=format&fit=crop", verificado: false },
  { id: 6, marca: "Mercedes-Benz", modelo: "Clase C", anio: 2022, tipo: "Lujo", ubicacion: "El Poblado", precioDia: 420000, descripcion: "Sedán de lujo, interior en cuero. Elegancia para reuniones y eventos.", transmision: "Automática", combustible: "Gasolina", pasajeros: 5, placa: "MBC 220", foto: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=900&q=80&auto=format&fit=crop", verificado: true },
  { id: 7, marca: "Renault", modelo: "Duster", anio: 2021, tipo: "SUV", ubicacion: "Sabaneta", precioDia: 140000, descripcion: "SUV práctica y ahorradora, perfecta para escapadas de fin de semana.", transmision: "Manual", combustible: "Gasolina", pasajeros: 5, placa: "RND 540", foto: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=900&q=80&auto=format&fit=crop", verificado: true },
  { id: 8, marca: "Chevrolet", modelo: "Onix", anio: 2022, tipo: "Sedán", ubicacion: "Itagüí", precioDia: 110000, descripcion: "Compacto, ágil y económico. Ideal para la ciudad y el día a día.", transmision: "Automática", combustible: "Gasolina", pasajeros: 5, placa: "CHV 088", foto: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=900&q=80&auto=format&fit=crop", verificado: true },
];

window.DP_TIPOS = ["Sedán", "SUV", "Pickup", "Lujo", "Eléctrico"];

window.formatCOP = function (n) { return "$" + Math.round(n).toLocaleString("es-CO"); };
